name: Build Free APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kaynak kodunu al
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle kurulumu
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle izinleri
        run: chmod +x gradlew

      - name: APK oluştur
        run: ./gradlew assembleDebug

      - name: APK'yı yükle
        uses: actions/upload-artifact@v4
        with:
          name: free-apk
          path: '**/build/outputs/apk/debug/*.apk'
